/* tslint:disable */
/* eslint-disable */
/**
 * Weather app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface GetLocationsResponseDto
 */
export interface GetLocationsResponseDto {
    /**
     * 
     * @type {number}
     * @memberof GetLocationsResponseDto
     */
    'count': number;
    /**
     * 
     * @type {Array<LocationDto>}
     * @memberof GetLocationsResponseDto
     */
    'locations': Array<LocationDto>;
}
/**
 * 
 * @export
 * @interface GetWeatherResponseDto
 */
export interface GetWeatherResponseDto {
    /**
     * 
     * @type {number}
     * @memberof GetWeatherResponseDto
     */
    'count': number;
    /**
     * 
     * @type {Array<LocationWeatherDto>}
     * @memberof GetWeatherResponseDto
     */
    'locations': Array<LocationWeatherDto>;
}
/**
 * 
 * @export
 * @interface HealthControllerCheck200Response
 */
export interface HealthControllerCheck200Response {
    /**
     * 
     * @type {string}
     * @memberof HealthControllerCheck200Response
     */
    'status'?: string;
    /**
     * 
     * @type {{ [key: string]: HealthControllerCheck200ResponseInfoValue; }}
     * @memberof HealthControllerCheck200Response
     */
    'info'?: { [key: string]: HealthControllerCheck200ResponseInfoValue; } | null;
    /**
     * 
     * @type {{ [key: string]: HealthControllerCheck200ResponseInfoValue; }}
     * @memberof HealthControllerCheck200Response
     */
    'error'?: { [key: string]: HealthControllerCheck200ResponseInfoValue; } | null;
    /**
     * 
     * @type {{ [key: string]: HealthControllerCheck200ResponseInfoValue; }}
     * @memberof HealthControllerCheck200Response
     */
    'details'?: { [key: string]: HealthControllerCheck200ResponseInfoValue; };
}
/**
 * 
 * @export
 * @interface HealthControllerCheck200ResponseInfoValue
 */
export interface HealthControllerCheck200ResponseInfoValue {
    [key: string]: string | any;

    /**
     * 
     * @type {string}
     * @memberof HealthControllerCheck200ResponseInfoValue
     */
    'status'?: string;
}
/**
 * 
 * @export
 * @interface HealthControllerCheck503Response
 */
export interface HealthControllerCheck503Response {
    /**
     * 
     * @type {string}
     * @memberof HealthControllerCheck503Response
     */
    'status'?: string;
    /**
     * 
     * @type {{ [key: string]: HealthControllerCheck200ResponseInfoValue; }}
     * @memberof HealthControllerCheck503Response
     */
    'info'?: { [key: string]: HealthControllerCheck200ResponseInfoValue; } | null;
    /**
     * 
     * @type {{ [key: string]: HealthControllerCheck200ResponseInfoValue; }}
     * @memberof HealthControllerCheck503Response
     */
    'error'?: { [key: string]: HealthControllerCheck200ResponseInfoValue; } | null;
    /**
     * 
     * @type {{ [key: string]: HealthControllerCheck200ResponseInfoValue; }}
     * @memberof HealthControllerCheck503Response
     */
    'details'?: { [key: string]: HealthControllerCheck200ResponseInfoValue; };
}
/**
 * 
 * @export
 * @interface LocationDto
 */
export interface LocationDto {
    /**
     * 
     * @type {number}
     * @memberof LocationDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof LocationDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof LocationDto
     */
    'countryCode': string;
}
/**
 * 
 * @export
 * @interface LocationWeatherDto
 */
export interface LocationWeatherDto {
    /**
     * 
     * @type {string}
     * @memberof LocationWeatherDto
     */
    'location': string;
    /**
     * 
     * @type {string}
     * @memberof LocationWeatherDto
     */
    'countryCode': string;
    /**
     * 
     * @type {Array<WeatherDto>}
     * @memberof LocationWeatherDto
     */
    'weather': Array<WeatherDto>;
}
/**
 * 
 * @export
 * @interface WeatherDto
 */
export interface WeatherDto {
    /**
     * 
     * @type {string}
     * @memberof WeatherDto
     */
    'timestamp': string;
    /**
     * 
     * @type {number}
     * @memberof WeatherDto
     */
    'temperatureCelsius': number;
    /**
     * 
     * @type {number}
     * @memberof WeatherDto
     */
    'pressure': number;
    /**
     * 
     * @type {number}
     * @memberof WeatherDto
     */
    'humidity': number;
    /**
     * 
     * @type {number}
     * @memberof WeatherDto
     */
    'windSpeedMetersPerSecond': number;
    /**
     * 
     * @type {number}
     * @memberof WeatherDto
     */
    'windDirection': number;
    /**
     * 
     * @type {number}
     * @memberof WeatherDto
     */
    'rainVolumePast3HoursMm'?: number;
    /**
     * 
     * @type {number}
     * @memberof WeatherDto
     */
    'snowVolumePast3HoursMm'?: number;
    /**
     * 
     * @type {number}
     * @memberof WeatherDto
     */
    'precipitationProbability': number;
    /**
     * 
     * @type {string}
     * @memberof WeatherDto
     */
    'weatherDescription': string;
    /**
     * 
     * @type {boolean}
     * @memberof WeatherDto
     */
    'isNight': boolean;
}

/**
 * LocationApi - axios parameter creator
 * @export
 */
export const LocationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationControllerGetLocations: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/locations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LocationApi - functional programming interface
 * @export
 */
export const LocationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LocationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async locationControllerGetLocations(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetLocationsResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.locationControllerGetLocations(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * LocationApi - factory interface
 * @export
 */
export const LocationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LocationApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        locationControllerGetLocations(options?: AxiosRequestConfig): AxiosPromise<GetLocationsResponseDto> {
            return localVarFp.locationControllerGetLocations(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LocationApi - object-oriented interface
 * @export
 * @class LocationApi
 * @extends {BaseAPI}
 */
export class LocationApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationApi
     */
    public locationControllerGetLocations(options?: AxiosRequestConfig) {
        return LocationApiFp(this.configuration).locationControllerGetLocations(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * MonitoringApi - axios parameter creator
 * @export
 */
export const MonitoringApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthControllerCheck: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MonitoringApi - functional programming interface
 * @export
 */
export const MonitoringApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MonitoringApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthControllerCheck(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthControllerCheck200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthControllerCheck(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MonitoringApi - factory interface
 * @export
 */
export const MonitoringApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MonitoringApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthControllerCheck(options?: AxiosRequestConfig): AxiosPromise<HealthControllerCheck200Response> {
            return localVarFp.healthControllerCheck(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MonitoringApi - object-oriented interface
 * @export
 * @class MonitoringApi
 * @extends {BaseAPI}
 */
export class MonitoringApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MonitoringApi
     */
    public healthControllerCheck(options?: AxiosRequestConfig) {
        return MonitoringApiFp(this.configuration).healthControllerCheck(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * WeatherApi - axios parameter creator
 * @export
 */
export const WeatherApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} startDate 
         * @param {string} endDate 
         * @param {Array<number>} [locationIds] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forecastControllerGetWeather: async (startDate: string, endDate: string, locationIds?: Array<number>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'startDate' is not null or undefined
            assertParamExists('forecastControllerGetWeather', 'startDate', startDate)
            // verify required parameter 'endDate' is not null or undefined
            assertParamExists('forecastControllerGetWeather', 'endDate', endDate)
            const localVarPath = `/weather`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString() :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString() :
                    endDate;
            }

            if (locationIds) {
                localVarQueryParameter['locationIds'] = locationIds.join(COLLECTION_FORMATS.csv);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WeatherApi - functional programming interface
 * @export
 */
export const WeatherApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WeatherApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} startDate 
         * @param {string} endDate 
         * @param {Array<number>} [locationIds] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async forecastControllerGetWeather(startDate: string, endDate: string, locationIds?: Array<number>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetWeatherResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.forecastControllerGetWeather(startDate, endDate, locationIds, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * WeatherApi - factory interface
 * @export
 */
export const WeatherApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WeatherApiFp(configuration)
    return {
        /**
         * 
         * @param {WeatherApiForecastControllerGetWeatherRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forecastControllerGetWeather(requestParameters: WeatherApiForecastControllerGetWeatherRequest, options?: AxiosRequestConfig): AxiosPromise<GetWeatherResponseDto> {
            return localVarFp.forecastControllerGetWeather(requestParameters.startDate, requestParameters.endDate, requestParameters.locationIds, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for forecastControllerGetWeather operation in WeatherApi.
 * @export
 * @interface WeatherApiForecastControllerGetWeatherRequest
 */
export interface WeatherApiForecastControllerGetWeatherRequest {
    /**
     * 
     * @type {string}
     * @memberof WeatherApiForecastControllerGetWeather
     */
    readonly startDate: string

    /**
     * 
     * @type {string}
     * @memberof WeatherApiForecastControllerGetWeather
     */
    readonly endDate: string

    /**
     * 
     * @type {Array<number>}
     * @memberof WeatherApiForecastControllerGetWeather
     */
    readonly locationIds?: Array<number>
}

/**
 * WeatherApi - object-oriented interface
 * @export
 * @class WeatherApi
 * @extends {BaseAPI}
 */
export class WeatherApi extends BaseAPI {
    /**
     * 
     * @param {WeatherApiForecastControllerGetWeatherRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherApi
     */
    public forecastControllerGetWeather(requestParameters: WeatherApiForecastControllerGetWeatherRequest, options?: AxiosRequestConfig) {
        return WeatherApiFp(this.configuration).forecastControllerGetWeather(requestParameters.startDate, requestParameters.endDate, requestParameters.locationIds, options).then((request) => request(this.axios, this.basePath));
    }
}


